services:
  lab-results-service:
    build: .
    container_name: ${NAME_UNDERSCORE}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://healthcare:healthcare_dev@postgres:5432/lab
      KAFKA_BOOTSTRAP: kafka:9092
      SERVICE_HOST_MODE: docker
      PORT_LAB_ORDERS_SERVICE: "8400"
      PORT_REFERENCE_RANGES_SERVICE: "8407"
      PORT_PATIENTS_SERVICE: "8100"
      PORT_NOTIFICATIONS_SERVICE: "9000"
      PORT_AUDIT_LOG_SERVICE: "8007"
      LOG_LEVEL: INFO
    ports:
      - "8401:8401"
    networks:
      - healthcare_net
    volumes:
      - ../../libs/py-healthcare-common:/opt/py-healthcare-common:ro
    command: >
      sh -c "pip install -e /opt/py-healthcare-common && python -m app.main"
